[package]
name = "cargo-tangerine"
version = "0.1.5"
authors = ["Alexandru Olaru <alxolr@gmail.com>"]
edition = "2021"
description = "Cargo workspaces monorepo manager, inspired by Lerna."
license = "MIT"
readme = "README.md"
default-run = "cargo-tangerine"
repository = "https://github.com/alxolr/cargo-tangerine"

[[bin]]
name = "cargo-tangerine"
path = "src/main.rs"

[profile.release]
lto = "thin"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
derive_more = { version = "2.1.1", features = ["from"] }
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["full"] }
toml = "1.1.4"
